### ISSUE TITLE
Cannot delete the categories

### ISSUE THREAD

**Issue by ovidiubularda** [andreiduca/snip-it#1]
I don't want to see a bunch a 'New category' items in my list.

**Comment by andreiduca** [comment]
This feature is already planned on the application development roadmap.
While the application is still in "beta" version, some features are yet to be implemented.

**Comment by andreiduca** [comment]
This feature has been released.

When you try to delete a category, you'll be presented with two options:
- delete the category with all its containing snippets
- delete the category, but keep all its snippets in the 'uncategorized' section

Check it out at https://snipit.xyz
