### ISSUE TITLE
Code editor instead of textarea field

### ISSUE THREAD

**Issue by rbl-eliseimiron** [andreiduca/snip-it#3]
1. Could be very useful a code editor instead of textarea field.
2. Resize option for categories and code snippet columns.

**Comment by andreiduca** [comment]
I have created #4 for point 2 so we can label and track the separate issues accordingly.

**Comment by andreiduca** [comment]
Point 2. was closed in issue #4 .

**Comment by andreiduca** [comment]
Moving this to Bitbucket: https://bitbucket.org/andreiduca/snip-it-client/issues/1/code-editor-instead-of-textarea-field
